import Navbar from './components/Navbar'
import './globals.css'
import Categories from './components/Categories'
import FooterHero from './components/FooterHero'
import Footer from './components/Footer'
import { Providers } from '@/provider'

export const metadata = {
  title: 'Insider_App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Navbar/>
        {children}
        <FooterHero/>
        <Footer/>
        </Providers>
        </body>
    </html>
  )
}
